# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_home_window(object):
    def setupUi(self, home_window):
        home_window.setObjectName("home_window")
        home_window.resize(1366, 768)
        home_window.setMaximumSize(QtCore.QSize(16777215, 16777215))
        home_window.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(home_window)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 100, 100))
        self.frame.setMaximumSize(QtCore.QSize(100, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.imgLabel = QtWidgets.QLabel(self.frame)
        self.imgLabel.setGeometry(QtCore.QRect(0, 0, 100, 100))
        self.imgLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.imgLabel.setText("")
        self.imgLabel.setPixmap(QtGui.QPixmap("../img/logo1.jpeg"))
        self.imgLabel.setObjectName("imgLabel")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(100, 0, 16777215, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.titleBarLabel = QtWidgets.QLabel(self.frame_2)
        self.titleBarLabel.setGeometry(QtCore.QRect(0, 0, 16777215, 40))
        self.titleBarLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.titleBarLabel.setFont(font)
        self.titleBarLabel.setStyleSheet("background-color: rgb(44, 28, 28);\n"
"color: rgb(255, 255, 255);")
        self.titleBarLabel.setObjectName("titleBarLabel")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(100, 40, 16777215, 61))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 85))
        self.frame_3.setStyleSheet("background-color: rgb(44, 28, 28);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.setupPageBtn = QtWidgets.QPushButton(self.frame_3)
        self.setupPageBtn.setGeometry(QtCore.QRect(30, 10, 100, 40))
        self.setupPageBtn.setMinimumSize(QtCore.QSize(100, 40))
        self.setupPageBtn.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.setupPageBtn.setFont(font)
        self.setupPageBtn.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 250, 250);\n"
"    background-color: rgb(255, 154, 3);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 154, 3);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 154, 3);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/icons/24x24/cil-settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setupPageBtn.setIcon(icon)
        self.setupPageBtn.setObjectName("setupPageBtn")
        self.devicePageBtn = QtWidgets.QPushButton(self.frame_3)
        self.devicePageBtn.setGeometry(QtCore.QRect(190, 10, 100, 40))
        self.devicePageBtn.setMinimumSize(QtCore.QSize(100, 40))
        self.devicePageBtn.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.devicePageBtn.setFont(font)
        self.devicePageBtn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 154, 3);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 154, 3);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 154, 3);\n"
"}")
        self.devicePageBtn.setIcon(icon)
        self.devicePageBtn.setObjectName("devicePageBtn")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(100, 40, 16777215, 1))
        self.frame_4.setMinimumSize(QtCore.QSize(0, 1))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 1))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 100, 1366, 668))
        self.stackedWidget.setMinimumSize(QtCore.QSize(1366, 668))
        self.stackedWidget.setObjectName("stackedWidget")
        self.setupPage = QtWidgets.QWidget()
        self.setupPage.setObjectName("setupPage")
        self.groupBox = QtWidgets.QGroupBox(self.setupPage)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 501, 241))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comPortComboBox = QtWidgets.QComboBox(self.groupBox)
        self.comPortComboBox.setGeometry(QtCore.QRect(100, 40, 131, 22))
        self.comPortComboBox.setObjectName("comPortComboBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.baudrateComboBox = QtWidgets.QComboBox(self.groupBox)
        self.baudrateComboBox.setGeometry(QtCore.QRect(100, 90, 131, 22))
        self.baudrateComboBox.setObjectName("baudrateComboBox")
        self.parityComboBox = QtWidgets.QComboBox(self.groupBox)
        self.parityComboBox.setGeometry(QtCore.QRect(100, 140, 131, 22))
        self.parityComboBox.setObjectName("parityComboBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(260, 40, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.dataBitsComboBox = QtWidgets.QComboBox(self.groupBox)
        self.dataBitsComboBox.setGeometry(QtCore.QRect(340, 40, 131, 22))
        self.dataBitsComboBox.setObjectName("dataBitsComboBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(260, 90, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.stopBitComboBox = QtWidgets.QComboBox(self.groupBox)
        self.stopBitComboBox.setGeometry(QtCore.QRect(340, 90, 131, 22))
        self.stopBitComboBox.setObjectName("stopBitComboBox")
        self.connectComPortBtn = QtWidgets.QPushButton(self.groupBox)
        self.connectComPortBtn.setGeometry(QtCore.QRect(190, 190, 151, 23))
        self.connectComPortBtn.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 250, 250);\n"
"    background-color: rgb(255, 154, 3);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 154, 3);\n"
"   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 154, 3);\n"
"}")
        self.connectComPortBtn.setObjectName("connectComPortBtn")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(260, 140, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comPortStatusLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.comPortStatusLineEdit.setEnabled(False)
        self.comPortStatusLineEdit.setGeometry(QtCore.QRect(340, 140, 131, 20))
        self.comPortStatusLineEdit.setObjectName("comPortStatusLineEdit")
        self.groupBox_3 = QtWidgets.QGroupBox(self.setupPage)
        self.groupBox_3.setGeometry(QtCore.QRect(530, 10, 391, 241))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.setupPage)
        self.groupBox_4.setGeometry(QtCore.QRect(940, 9, 411, 641))
        self.groupBox_4.setObjectName("groupBox_4")
        self.terminalTextEdit = QtWidgets.QTextEdit(self.groupBox_4)
        self.terminalTextEdit.setGeometry(QtCore.QRect(10, 20, 391, 611))
        self.terminalTextEdit.setObjectName("terminalTextEdit")
        self.groupBox_5 = QtWidgets.QGroupBox(self.setupPage)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 260, 911, 391))
        self.groupBox_5.setObjectName("groupBox_5")
        self.stackedWidget.addWidget(self.setupPage)
        self.devicePage = QtWidgets.QWidget()
        self.devicePage.setObjectName("devicePage")
        self.groupBox_2 = QtWidgets.QGroupBox(self.devicePage)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 30, 591, 291))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.comPortComboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comPortComboBox_2.setGeometry(QtCore.QRect(100, 40, 131, 22))
        self.comPortComboBox_2.setObjectName("comPortComboBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.baudrateComboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.baudrateComboBox_2.setGeometry(QtCore.QRect(100, 90, 131, 22))
        self.baudrateComboBox_2.setObjectName("baudrateComboBox_2")
        self.parityComboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.parityComboBox_2.setGeometry(QtCore.QRect(100, 140, 131, 22))
        self.parityComboBox_2.setObjectName("parityComboBox_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 140, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.devicePage)
        self.lineEdit.setGeometry(QtCore.QRect(350, 420, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.stackedWidget.addWidget(self.devicePage)
        home_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(home_window)
        QtCore.QMetaObject.connectSlotsByName(home_window)

    def retranslateUi(self, home_window):
        _translate = QtCore.QCoreApplication.translate
        home_window.setWindowTitle(_translate("home_window", "True Tracker - Home"))
        self.titleBarLabel.setText(_translate("home_window", " Access Control System"))
        self.setupPageBtn.setText(_translate("home_window", "Setup"))
        self.devicePageBtn.setText(_translate("home_window", "Devices"))
        self.groupBox.setTitle(_translate("home_window", "COM Device"))
        self.label.setText(_translate("home_window", "COM Port :"))
        self.label_2.setText(_translate("home_window", "Baudrate :"))
        self.label_3.setText(_translate("home_window", "Parity      :"))
        self.label_4.setText(_translate("home_window", "Data Bits :"))
        self.label_5.setText(_translate("home_window", "Stop Bits :"))
        self.connectComPortBtn.setText(_translate("home_window", "Connect"))
        self.label_9.setText(_translate("home_window", "Status    :"))
        self.groupBox_3.setTitle(_translate("home_window", "Additional Settings"))
        self.groupBox_4.setTitle(_translate("home_window", "Terminal"))
        self.groupBox_5.setTitle(_translate("home_window", "IP Device"))
        self.groupBox_2.setTitle(_translate("home_window", "COM Device"))
        self.label_6.setText(_translate("home_window", "COM Port :"))
        self.label_7.setText(_translate("home_window", "Baudrate :"))
        self.label_8.setText(_translate("home_window", "Parity      :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    home_window = QtWidgets.QMainWindow()
    ui = Ui_home_window()
    ui.setupUi(home_window)
    home_window.show()
    sys.exit(app.exec_())
