# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(800, 350)
        RegisterWindow.setMaximumSize(QtCore.QSize(800, 350))
        self.centralwidget = QtWidgets.QWidget(RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 350))
        self.frame.setMaximumSize(QtCore.QSize(800, 350))
        self.frame.setStyleSheet("background-color: rgb(44, 28, 28);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.firstNameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.firstNameLineEdit.setGeometry(QtCore.QRect(350, 50, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.firstNameLineEdit.setFont(font)
        self.firstNameLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.firstNameLineEdit.setText("")
        self.firstNameLineEdit.setObjectName("firstNameLineEdit")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(220, 90, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(220, 170, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.lastNameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.lastNameLineEdit.setGeometry(QtCore.QRect(350, 90, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.lastNameLineEdit.setFont(font)
        self.lastNameLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lastNameLineEdit.setText("")
        self.lastNameLineEdit.setObjectName("lastNameLineEdit")
        self.emailLineEdit = QtWidgets.QLineEdit(self.frame)
        self.emailLineEdit.setGeometry(QtCore.QRect(350, 130, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.emailLineEdit.setFont(font)
        self.emailLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.emailLineEdit.setText("")
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(220, 130, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(220, 210, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(220, 50, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.usernameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.usernameLineEdit.setGeometry(QtCore.QRect(350, 170, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.usernameLineEdit.setFont(font)
        self.usernameLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.usernameLineEdit.setText("")
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.pwdLineEdit = QtWidgets.QLineEdit(self.frame)
        self.pwdLineEdit.setGeometry(QtCore.QRect(350, 210, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.pwdLineEdit.setFont(font)
        self.pwdLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pwdLineEdit.setText("")
        self.pwdLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdLineEdit.setObjectName("pwdLineEdit")
        self.registerBtn = QtWidgets.QPushButton(self.frame)
        self.registerBtn.setGeometry(QtCore.QRect(340, 270, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.registerBtn.setFont(font)
        self.registerBtn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 154, 3);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 154, 3);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 154, 3);\n"
"}")
        self.registerBtn.setObjectName("registerBtn")
        RegisterWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "Access Control System - Register"))
        self.label_2.setText(_translate("RegisterWindow", "Last Name :"))
        self.label_4.setText(_translate("RegisterWindow", "Username  :"))
        self.label_3.setText(_translate("RegisterWindow", "Email Id    :"))
        self.label_5.setText(_translate("RegisterWindow", "Password  :"))
        self.label.setText(_translate("RegisterWindow", "First Name :"))
        self.registerBtn.setText(_translate("RegisterWindow", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterWindow = QtWidgets.QMainWindow()
    ui = Ui_RegisterWindow()
    ui.setupUi(RegisterWindow)
    RegisterWindow.show()
    sys.exit(app.exec_())
